"""
build_chart_data.py
===================
Master assembler: runs VMT, GHG, and equity pipelines, then writes a single
`chart_data.js` file that the HTML page loads via <script src="data/chart_data.js">.

The JS file defines window.SB375Data so Chart.js initialization in the HTML
can reference it directly — no fetch(), no server required (works with file://).

Run:
  cd data/
  python build_chart_data.py

Outputs:
  data/vmt_scenarios.csv
  data/ghg_scenarios.csv
  data/equity_exposure.csv
  data/chart_data.js          ← loaded by sb375-lessons-learned.html
"""

import json
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).parent

# ──────────────────────────────────────────────────────────────────────────────
# 1. Run all three sub-scripts (they write their own *_js.json side-files)
# ──────────────────────────────────────────────────────────────────────────────
scripts = ["build_vmt_scenarios.py", "build_ghg_scenarios.py", "build_equity_exposure.py"]
for script in scripts:
    print(f"\n{'='*60}\nRunning {script} …\n{'='*60}")
    result = subprocess.run([sys.executable, str(HERE / script)], check=True)

# ──────────────────────────────────────────────────────────────────────────────
# 2. Load computed JSON payloads
# ──────────────────────────────────────────────────────────────────────────────
vmt_data    = json.loads((HERE / "vmt_scenarios_js.json").read_text())
ghg_data    = json.loads((HERE / "ghg_scenarios_js.json").read_text())
equity_data = json.loads((HERE / "equity_exposure_js.json").read_text())

# ──────────────────────────────────────────────────────────────────────────────
# 3. Assemble JS file
# ──────────────────────────────────────────────────────────────────────────────
# Human-readable scenario labels for Chart.js legends & tooltips
SCENARIO_LABELS = {
    "california_today_bau"                : "California today (BAU)",
    "ca_29pct_target_path"                : "CA 29 % reduction target path",
    "colorado_budget_lock"                : "Colorado-style budget lock",
    "minnesota_capacity_trigger"          : "Minnesota-style capacity trigger",
    "virginia_scoring"                    : "Virginia-style project scoring",
    "massachusetts_caps"                  : "Massachusetts-style emission caps",
    "combined_approach"                   : "Combined approach (all four tools)",
    "massachusetts_style_annual_cap_ceiling": "MA-style annual cap (reference ceiling)",
}

# Brand-coordinated palette (matches site CSS tokens)
PALETTE = {
    "california_today_bau"                : "#c0392b",   # red — status quo
    "ca_29pct_target_path"                : "#27ae60",   # green — required path
    "colorado_budget_lock"                : "#1f6e8c",   # steel blue
    "minnesota_capacity_trigger"          : "#e07b39",   # orange
    "virginia_scoring"                    : "#2d7d56",   # forest green
    "massachusetts_caps"                  : "#7b4fa6",   # purple
    "combined_approach"                   : "#c47d14",   # gold
    "massachusetts_style_annual_cap_ceiling": "#9b59b6", # soft purple (reference)
    "current_burden"                      : "#c0392b",
    "after_combined"                      : "#27ae60",
}

js_block = f"""// =============================================================
// SB 375 → SB 1087  ·  Chart Data
// Generated by data/build_chart_data.py
// ALL VALUES ARE CONCEPTUAL / ILLUSTRATIVE unless noted otherwise.
// Replace arrays with real model outputs when Caltrans / EMFAC / 
// CalEnviroScreen data are integrated.
// =============================================================
window.SB375Data = {{

  // ── VMT Scenarios ──────────────────────────────────────────
  // Index basis: 2001 Caltrans per-capita VMT peak = 100
  // Years: {vmt_data["years"]}
  vmt: {{
    years   : {json.dumps(vmt_data["years"])},
    meta    : {json.dumps(vmt_data["metadata"], indent=4)},
    labels  : {json.dumps(SCENARIO_LABELS)},
    palette : {json.dumps(PALETTE)},
    scenarios: {{
{chr(10).join(
  f'      {json.dumps(k)}: {json.dumps(v)},'
  for k, v in vmt_data["scenarios"].items()
)}
    }}
  }},

  // ── GHG Trajectories ───────────────────────────────────────
  // Index basis: 2025 CA transportation GHG = 100
  // Years: {ghg_data["years"]}
  ghg: {{
    years   : {json.dumps(ghg_data["years"])},
    meta    : {json.dumps(ghg_data["metadata"], indent=4)},
    labels  : {json.dumps(SCENARIO_LABELS)},
    palette : {json.dumps(PALETTE)},
    scenarios: {{
{chr(10).join(
  f'      {json.dumps(k)}: {json.dumps(v)},'
  for k, v in ghg_data["scenarios"].items()
)}
    }}
  }},

  // ── Equity / Health Exposure ────────────────────────────────
  // Pollution burden index by corridor (I-710 = 100, highest burden)
  equity: {{
    corridor_labels : {json.dumps(equity_data["corridor_labels"])},
    before_values   : {json.dumps(equity_data["before_values"])},
    after_combined  : {json.dumps(equity_data["after_combined"])},
    dac_pcts        : {json.dumps(equity_data["dac_pcts"])},
    by_reform       : {json.dumps(equity_data["by_reform"])},
    meta            : {json.dumps(equity_data["metadata"], indent=4)},
    palette         : {json.dumps(PALETTE)}
  }}

}};
"""

out_path = HERE / "chart_data.js"
out_path.write_text(js_block, encoding="utf-8")
print(f"\n✅  chart_data.js written → {out_path}")
print("   Load in HTML with:  <script src=\"data/chart_data.js\"></script>")
